### PR TITLE
Last 3 tasks

### PR DESCRIPTION
**Pull request by tmcdos**
1) Bug fixing of 1 panel open that shows at 50% height and panels that don't show afterwards
2) Add tab for panel 1 also in full screen (just like the other panels)
3) New styles for tabs, showing also the icons of the apps in them
-----
4) Responsive layout fixes - NOT yet implemented

### CODE REVIEW

**Comment by titpetric** [comment]
Hello. Could you please revert changes to `.eslintrc.js` as the style guide is fixed across all projects, and update the pull request accordingly after the change, so we may review. Thank you.

**Comment by titpetric** [comment]
To clarify, only `.eslintrc.js` is the problem. I am happy where we are in regards to the JS front in regards to curly braces, end line semicolons, I might only be convinced for `comma-dangle` if @darh is fine with the suggested change. Effectively, it's a minor change so this part should be +1.

I actually appreciate adding a scss/css lint fix into the fold, but I'm going to need @juan-non and @darh to sign off on the changes to vue.config.js here, hopefully it doesn't disturb their current css/scss flow.

**Comment by darh** [comment]
👍 👍  for hardening the syntax style.

I'm having a hard time to support the Allman since it opens the possibility to statement insertion. Please consider OTBS. Ref: https://en.wikipedia.org/wiki/Indentation_style.

Regarding the actual fix: it is leaving leading spaces on lines where curly brackets are moved down. Something that could probably be fixed through eslint, right?

Regarding commit messages, please read https://chris.beams.io/posts/git-commit/.

**Comment by darh** [comment]
Another thing -- let's be consistent with the naming schema for yarn commands/scripts: colon vs dash => `test:unit` vs `lint-css`. I don't mind if you change test:unit, just let's keep it consistent. 
`fix` suffix should/must indicate that command will change the files.

_Nitpicking_ :)

**Comment by tmcdos** [comment]
I will summarize:
1) you want me to change my style from Allman to 1TBS - I do not want to do that but if you insist on this (because, hey - it is THE ONLY TRUE BRACE STYLE) I will become less productive and the side effect will be more billable time
2) I also noticed that StyleLint does not properly indent when the opening bracket in a CSS selector is moved down - we should probably fire an issue on GitHub
3) I agree that commit message needs reworking
4) I agree that script names in `package.json` were not consistent

**Comment by crustcrm1** [comment]
About the styles: let's just use the style guide that is fixed across all projects. :)

**Comment by titpetric** [comment]
@tmcdos to clarify, we want you to stick to the already existing style which is applied across 4 projects and used by about 5 developers, meaning OTBS, and not particularly because of it's misfortunate naming. Pre-commit lint should fix any of your own preferences automatically :)

**Comment by titpetric** [comment]
Changes merged as they LGTM. Small cleanup tasks for the future:

1. I'd like to keep css/scss linting (was already done in original commit),
2. remove unused packages from package.json (vuedraggable)

**Comment by tmcdos** [comment]
1. You are free to setup whatever type of style you want your projects (chrome, admin, crm, messaging) to follow and I will adhere to your choice. I am not going to be responsible for changing your style guide, for any reason.
2. Done

**Pull request merged**
